---   
- name: restart httpd
  service:
    name: httpd
    state: restarted
    enabled: true

- name: configuring firewalld
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - http
    - https

