B
---
- name: Installing a required packages
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ pkgs }}"

- name: Generating a ssl certificate
  include_tasks: ssl.yml  
  when: ssl_engine is defined and ssl_engine | lower == "yes"

- name: "Preparing the configuration file for {{ cert_common_name }}"
  template:
    src: "{{ cert_org_name }}.conf.j2"
    dest: /etc/httpd/conf.d/{{ cert_org_name }}.conf

- name: "Ensuring the document root exists"
  file:
    path: "{{ doc_root }}"
    state: directory
    mode: "0755"

- block:
    - name: "Installing a passlib module"
      ansible.builtin.pip:
        name:  passlib

    - name: Applying a authentication on the website
      template:
        src: htaccess.j2
        dest: "{{ doc_root }}/.htaccess"

    - name: Add a user to a password file and ensure permissions are set
      community.general.htpasswd:
        path: /etc/httpd/conf/.htpasswd
        name: "{{ item.name }}"
        password: "{{  item.passwd }}"
        owner: root
        group: apache
        mode: 0640
        crypt_scheme: md5_crypt
      loop: "{{ users }}"
  when: allow_override is defined and allow_override | lower == "all"

- name: "Preparing the index page"
  template:
    src: index.html.j2
    dest: "{{ doc_root }}/index.html"

- name: CONFIGURE SELINUX, SERVICES and FIREWALL  
  include_tasks: other.yml
